### ISSUE TITLE
Do we want to force record's id to be UUID?

### ISSUE THREAD

**Issue by Natim** [mozilla-services/kinto#102]
For now Cliquet ressources can be any kind of objects.

In the scope of kinto, do we want to say that a record id must be a UUID?

**Comment by n1k0** [comment]
I vote for this; imho uuids are opaque, fast when properly indexed, well known and tooled. I could see people wanting us to support key-value like stores, eg. getting a setting name by its id which would be the primary key, though I'm not really sure we want to support/encourage this approach.

I'm not totally on the fence though. Thoughts?

**Comment by Natim** [comment]
For now we are using UUID but we plan to let the server administrator configure it with https://github.com/mozilla-services/cliquet/issues/292 in the future.
