### ISSUE TITLE
Attach record data to BATCH 412 responses.

### ISSUE THREAD

**Issue by n1k0** [mozilla-services/kinto#122]
In order for clients to properly notify from conflicting records on BATCH operations, it would be useful to have the record data attached to the JSON response body, eg.

```json
{
  "errno": 999,
  "message": "Failed batch subrequest",
  "code": 412,
  "error": "Precondition Failed",
  "data": { "id": "…" }
}
```

Also, it would be nice to have a dedicated errno and message for races.

**Comment by Natim** [comment]
I wonder if we shoudn't do the same for ``409 Conflict``

**Comment by n1k0** [comment]
Yes, probably.

**Comment by leplatrem** [comment]
We already have a ``details`` field in error responses, so it makes sense to use it for 412.

AFAIK it is already present on 409, see http://cliquet.readthedocs.org/en/latest/api/errors.html#conflict-errors

> Since this is something that concerns the protocol, it will be implemented in *Cliquet*.

**Comment by Natim** [comment]
:+1:
