### ISSUE TITLE
Missing CORS header on /v1/buckets/default/collections/tasks/records

### ISSUE THREAD

**Issue by n1k0** [mozilla-services/kinto#132]
> 09:19:55,733 Blocage d'une requête multi-origines (Cross-Origin Request) : la politique « Same Origin » ne permet pas de consulter la ressource distante située sur http://0.0.0.0:8888/v1/buckets/default/collections/tasks/records?_since=1436512795672. Raison : l'en-tête CORS « Access-Control-Allow-Origin » est manquant.1 <inconnu>

**Comment by leplatrem** [comment]
This happens only when going the default bucket view.

Indeed, when using the «absolute» bucket id, the problem disappears.

**Comment by Natim** [comment]
We should use the reapply_cors decorator on the default pyramid view.

**Comment by leplatrem** [comment]
:+1: !

**Comment by leplatrem** [comment]
I can't reproduce locally:

```$ http "http://0.0.0.0:8888/v1/buckets/default/collections/articles/records?_since=1234" Origin:localhost:8000 --auth=user:pass
HTTP/1.1 200 OK
Access-Control-Allow-Origin: *
Access-Control-Expose-Headers: Backoff, Retry-After, Alert, Next-Page, Total-Records, Last-Modified, ETag
Content-Length: 11
Content-Type: application/json; charset=UTF-8
Date: Fri, 10 Jul 2015 10:39:56 GMT
Etag: "1436524796357"
Last-Modified: Fri, 10 Jul 2015 10:39:56 GMT
Server: waitress
Total-Records: 0

{
    "data": []
}
```

The header ``Access-Control-Allow-Origin: *`` seems to be returned.

**Comment by Natim** [comment]
You can reproduce on 304:

    $ http "http://0.0.0.0:8888/v1/buckets/default/collections/articles/records?_since=1436524796357" Origin:localhost:8000 --auth=user:pass
