### ISSUE TITLE
Info link on error pages does not mention kinto

### ISSUE THREAD

**Issue by leplatrem** [mozilla-services/kinto#138]
```json
{
    "code": 500, 
    "errno": 999, 
    "error": "Internal Server Error", 
    "info": "https://github.com/mozilla-services/cliquet/issues/", 
    "message": "A programmatic error occured, developers have been informed."
}
```

In the ``info`` field, we should point the kinto issues repository instead

**Comment by Natim** [comment]
We should use a configuration variable here: https://github.com/mozilla-services/cliquet/blob/master/cliquet/views/errors.py#L104

**Comment by Natim** [comment]
Refs: https://github.com/mozilla-services/cliquet/issues/385

**Comment by Natim** [comment]
It has been merged.
