### ISSUE TITLE
Untrusted connection on dev server instance

### ISSUE THREAD

**Issue by n1k0** [mozilla-services/kinto#139]
![screen shot 2015-07-14 at 19 40 59](https://cloud.githubusercontent.com/assets/41547/8680250/5507597e-2a60-11e5-90fb-f5f20111d64d.png)

Error code: `sec_error_expired_certificate`

**Comment by leplatrem** [comment]
> The certificate expired on 14/07/2015 14:00. 

:smile:

**Comment by Natim** [comment]
ping @mostlygeek @Micheletto @deanwilson

**Comment by deanwilson** [comment]
The request for a new cert went in yesterday i think. I'll check on the status when the US is awake.

**Comment by Natim** [comment]
I just updated the ELB certificate everything should work as expected. Next update in July 2017
