### ISSUE TITLE
Deploy Kinto on https://pay-storage.dev.mozaws.net/v1/

### ISSUE THREAD

**Issue by Natim** [mozilla-services/kinto#145]
The payment team will need a storage service deployed for their concrete demo:

http://pay.dev.mozaws.net/

**Comment by ametaireau** [comment]
Let it be https://payments-storage.dev.mozaws.net.

**Comment by leplatrem** [comment]
I am wondering if the Github issues are a good place to track deployment tasks for Mozilla internal stuff.
Our Trello is probably more appropriate. What do you think ?

**Comment by Natim** [comment]
IMHO, the good place for deployment request is Bugzilla. I put it here because I wanted @kumar303 and @andymckay to be able to follow.

**Comment by ametaireau** [comment]
+1. I added to the trello this afternoon actually. Maybe we should close here and ping them when it's been deployed.
