### ISSUE TITLE
PostgreSQL by default ?

### ISSUE THREAD

**Issue by leplatrem** [mozilla-services/kinto#3]
* put ``cliquet[postgresql]`` in requirements
* put storage_url in config (default postgres:postgres@localhost/postgres)

**Comment by ametaireau** [comment]
Yes, I believe that makes the most sense to have kinto persist on disk by default. Redis / Memory are too volatile to make them defaults here.

**Comment by Natim** [comment]
It depends what default means, for me default are to help the dev to get started. Not default configuration for production.

Maybe the answer is not the same for kinto and cliquet on this. But IMHO the default should be something easier to setup than postgresql.

**Comment by Natim** [comment]
Btw on defaut Redis configuration, persistence on disk is activated.

**Comment by ametaireau** [comment]
If we need to differentiate between defaults for the devs and defaults for prod, then we probably should  have two different set of configuration files.

I don't consider postgres to be something harder than postgres to install (but yes, that's a personal thing I believe). So, even if it is (hard to install), we should document how to install it (with a docker, yo).

I wasn't aware for [redis persisting on disk by default](http://redis.io/topics/persistence), cool!

> The suggested (and default) policy is to fsync every second. It is both very fast and pretty safe. The always policy is very slow in practice (although it was improved in Redis 2.0) – there is no way to make fsync faster than it is.

**Comment by leplatrem** [comment]
PostgreSQL is a lot more easy to install than Redis (see docs), but since we don't have any other session backend implementation, using psql by default does not prevent us from running Redis!

We could consider defaulting to PostgreSQL once we have session backend running on it :)

**Comment by leplatrem** [comment]
Since the default test database is postgres in cliquet, there is no database creation step
