### ISSUE TITLE
Define how we want to handle principals

### ISSUE THREAD

**Issue by ametaireau** [mozilla-services/kinto#35]
*what they are and how to obtain them?*

(This is a copy/paste from @natim on #33)

# Users and principals

The authentication process let us get some useful information about our user:

 - Unique ID
 - Email address
 - Scopes

All the authentication scheme doesn't let us have all the same information.

Our proposal is to build a list of principals for a user with all the information we've got including uid, email, scopes to build a user principals as well as a list of principals coming from the configuration, organisations  setup and collection setup.

As a example, if I (uid=4567, email=natim@example.com) get connected using FxA with the *profile* and *payments* scope and that I have access to the servicedesnuages bucket I will have the following principals:

    ["user:4567", "user:natim@example.com",
     "bucket:servicedesnuages", "scope:payements", "scope:profile"]

Then some permissions can be set to any of this principals to let me have them.

For example, on a collection I can set:

    {"read_all_records": ["bucket:servicedesnuages"]}

**Comment by ametaireau** [comment]
It's interesting to note that these information we can get about our users aren't actually all mandatory. We should have one which is mandatory (and acts as a kind of identifier of the user).

Also, I would be more specific about the principals you can get out of this, for instance, if the principal is coming as an `uuid`, then we should put this information in the principals.

```python
["uuiid:4567", "email:natim@example.com",
 "org:servicedesnuages", "scope:payements", "scope:profile"]
```

**Comment by ametaireau** [comment]
I don't quite get what "I have access to the servicedesnuages org" actually means and if that's something we should support for our first iteration.

**Comment by Natim** [comment]
What I was thinking is to use the bucket list of user as a principal.

The principal ``org:servicedenuages`` means all people admin of the bucket *servicedenuages*

**Comment by ametaireau** [comment]
See #34 for a definition of what buckets are.

**Comment by Natim** [comment]
This have been discussed and implemented.
