### ISSUE TITLE
Add hosted docker image for speedup / deployment

### ISSUE THREAD

**Issue by kumar303** [mozilla-services/kinto#55]
The docker image currently must be built from source and will require a re-run of dependency installation any time the source changes (due to how layering works). Also, it is harder to deploy images since the code must be shipped independently. Instead, if you hosted the image on [docker hub](https://registry.hub.docker.com/) we could pull the image which would be a little faster and allow for direct deployment. One nice thing about this is that docker hub will automatically rebuild the image each time you push a commit to master.

Ask us if you want examples on how to set this up. Here is one of our pre-built images: https://registry.hub.docker.com/u/mozillamarketplace/solitude/

We can link to it in our docker compose file like this:
````
solitude:
  image: mozillamarketplace/solitude
  ...
````
This lets us also deploy images directly to a server.

**Comment by Natim** [comment]
We will for each release of kinto for now on.

**Comment by ametaireau** [comment]
This is here: https://registry.hub.docker.com/u/mozillastorage/kinto/

Now all commits to master will build a new docker image. We might change this in the future to only build tags.

@leplatrem @Natim @tarekziade @n1k0 if you have an account, I can add you to the mozilla-storage organisation.

**Comment by kumar303** [comment]
Awesome, thanks!

**Comment by kumar303** [comment]
it seems to be working in my patch here https://github.com/mozilla/payments-env/pull/34
