### ISSUE TITLE
Add a create permission doesn't looks to work

### ISSUE THREAD

**Issue by Natim** [mozilla-services/kinto#65]
```
echo '{"data": {}, "permissions": {"records:create": ["system.Authenticated"]}}' | http PUT http://localhost:8888/v1/buckets/mozilla/collections/payments -v --auth="$LOGIN:$PASSWORD"
```

The create permission is not set.

**Comment by leplatrem** [comment]
Indeed, I didn't write tests for ``records:create`` and ``groups:create``! We should do that!

**Comment by Natim** [comment]
Ah well as ``collections:create``

**Comment by Natim** [comment]
This has been done already: https://github.com/mozilla-services/kinto/commit/c5e01827f06a5c391615edb3779fa77135c3b395
