### ISSUE TITLE
Create parent objects if missing ?

### ISSUE THREAD

**Issue by leplatrem** [mozilla-services/kinto#70]
Currently, in order to post a record in a new collection, the client shall previously perform two ``PUT`` requests (on bucket and on collection).

I believe this is not very convenient for clients (@n1k0?).

What if, on record POST/PUT, we create the collection and the bucket ? *(if they are missing and if the client is allowed to)*

**Comment by Natim** [comment]
This is something we want at least for the default bucket.

**Comment by leplatrem** [comment]
Is the «default bucket» what I naively called «personal bucket» ?

**Comment by Natim** [comment]
Actually we could have both:
- A default one where everybody could create collection and when looking for ``/buckets/default/collections`` will get only its collection
- A personal one created automatically for him ('~' or 'personal')
