### ISSUE TITLE
Include cliquet-fxa by default

### ISSUE THREAD

**Issue by leplatrem** [mozilla-services/kinto#72]
* Add it to setup.py deps (optional require ?)
* Add it to ``config/kinto.ini``

If we disagree on this, then clean-up ``config/kinto.ini`` and remove mentions of ``fxa``

**Comment by Natim** [comment]
IMHO documentation about it could be enough.

**Comment by Natim** [comment]
Fixed with https://github.com/mozilla-services/kinto/pull/81/files
