### ISSUE TITLE
Kinto just needs cliquet as a dependency not cliquet[postgresql,monitoring]

### ISSUE THREAD

**Issue by Natim** [mozilla-services/kinto#89]
By default Kinto now uses the memory backend.

**Comment by Natim** [comment]
Fixed with https://github.com/mozilla-services/kinto/commit/84cb825dec791a08eb806fb006feb171361d92ee#diff-2eeaed663bd0d25b7e608891384b7298L18

**Comment by Natim** [comment]
Well for now, cliquet is not able to run without postgresql. See mozilla-services/cliquet#340

**Comment by leplatrem** [comment]
Done.
